# syntax=docker/dockerfile:1

# This is the Dockerfile for the module_example.

FROM python:3.11
LABEL org.opencontainers.image.source=https://github.com/pal03377/Athena-New

# Environment variable Python in Docker
ENV PYTHONUNBUFFERED=1

WORKDIR /code

# Poetry
RUN pip install --no-cache-dir poetry==1.5.0

# Dependencies
COPY pyproject.toml poetry.lock ./
# athena module (from the Dockerfile in the athena folder)
COPY --from=athena /code /athena
# install dependencies
RUN poetry config virtualenvs.create true \
    && poetry config virtualenvs.in-project true \
    && poetry install --no-interaction --no-ansi

# re-install pytorch in the CPU version because we don't have a GPU
RUN poetry source add --priority=supplemental torch-stable https://download.pytorch.org/whl/ # Add the PyTorch repo
RUN poetry add torch==2.0.0+cpu # Install PyTorch

# Project files
COPY . ./

# poetry scripts don't work here
CMD poetry run python -m module_*