docker_nodes:
  - traefik_service_api: http://module_cofee_old:8080/api/http/services/
    segmentation_service_name: cofee-segmentation@docker
    embedding_service_name: cofee-embedding@docker
    clustering_service_name: cofee-clustering@docker
    trigger_route: /trigger