# Docker configuration backend
providers:
  docker:
    exposedbydefault: false
    endpoint: "unix:///var/run/docker.sock"
#    swarmMode: true

# Entrypoint configuration
entryPoints:
  web:
    address: ":4999"

# API and dashboard configuration
api:
  insecure: true
