strictness: low

autodetect: false

ignore-paths:
  - docs
  - module_cofee/module_cofee/protobuf

mypy:
    run: true
    options:
         ignore-missing-imports: true
         follow-imports: skip

pycodestyle:
  disable:
    - R0903
  max-line-length: 120

pylint:
    disable:
        - too-few-public-methods