strictness: low

autodetect: false

ignore-paths:
  - docs
  - module_text_cofee/module_text_cofee/protobuf
  - module_programming_themisml/extract_methods/languages
  - module_programming_themisml/extract_methods/method_parser_listener.py
  - module_programming_apted/convert_code_to_ast/languages

mypy:
  run: true
  options:
    ignore-missing-imports: true
    follow-imports: skip
  plugins: pydantic.mypy,sqlalchemy.ext.mypy.plugin

pycodestyle:
  disable:
    - R0903
  max-line-length: 120

pylint:
    disable:
        - too-few-public-methods