version: '3.8'

# This hosts the playground image in production. It only works in combination with docker-compose.prod.yml
# Usage: docker compose -f docker-compose.prod.yml -f docker-compose.playground.prod.yml up -d

services:

  playground:
    hostname: playground
    image: ls1tum/athena_playground:${ATHENA_TAG:-develop}

  log_viewer:
    hostname: log-viewer
    image: ls1tum/athena_log_viewer:${ATHENA_TAG:-develop}
    env_file:
      - ${ATHENA_ENV_DIR:-./env_example}/log_viewer.env
    volumes:
      # allow log viewer to access docker logs
      - /var/run/docker.sock:/var/run/docker.sock
