version: '3.8'

# This is the docker-compose file for the Athena Assessment Module Manager
# The Docker Compose configuration files for the individual modules can be found in their respective folders.

services:
  athena_assessment_module_manager:
    tty: true
    # Ensure that the containers from other docker-compose files can communicate with each other
    networks:
      - athena_network

networks:
  athena_network:
    name: athena_network
    driver: bridge