version: '3.8'

services:
  nginx:
    image: nginx:1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - athena_network

networks:
  athena_network:
    name: athena_network
    driver: bridge