version: '3.8'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - athena_network

networks:
  athena_network:
    name: athena_network
    driver: bridge