version: '3.8'

services:
  main:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - MODULE_NAME
    tty: true
    hostname: ${MODULE_NAME}
    networks:
      - athena_network
    environment:
      - OPENAI_API_KEY

networks:
  athena_network:
    name: athena_network
    driver: bridge