version: '3.8'

services:
  nextjs:
    image: node:18.16.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run build && npm start"
