version: '3.8'

# common module configuration

services:
  main:
    tty: true
    hostname: ${MODULE_NAME}
    networks:
      - athena_network

networks:
  athena_network:
    name: athena_network
    driver: bridge