name: Build Docker Images

# Build the Docker images for the the assessment module manager, the modules and the playground.
# Because the Python images depend on the athena Python package, the package is built first.

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

# prevent Docker image push conflicts
concurrency: 
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  find_images_to_build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Matrix
        id: set-matrix
        run: |
          IMAGE_NAMES=$(ls -d assessment_module_manager module_* playground | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=${IMAGE_NAMES}" > $GITHUB_OUTPUT

  build_image:
    needs: find_images_to_build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{fromJson(needs.find_images_to_build.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build athena image
        id: set-image
        run: |
          cd athena
          docker build -t athena .
          cd ..

      - name: Docker Login
        id: docker-login
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/Athena/${{ matrix.image }}
            ls1tum/athena_${{ matrix.image }}
          tags: |
            type=raw,value=${{ github.ref == 'refs/heads/develop' && 'develop' || github.sha }}
            type=raw,value=${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.sha }}

      - name: Get the current branch
        id: branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" > $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ATHENA_PR_NUMBER=${{ github.event.pull_request.number }}
            ATHENA_SHA=${{ github.sha }}
            ATHENA_BRANCH=${{ steps.branch.outputs.branch }}