name: Docker Images for Modules

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: ''
      push:
        description: 'Push to GitHub Container Registry'
        required: true
        default: 'false'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set Matrix
        id: set-matrix
        run: |
          MODULE_NAMES=$(ls -d module_* | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=${MODULE_NAMES}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build (and push) Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: MODULE_NAME=${{ matrix.module }}
          push: ${{ github.event.pull_request.base.ref == 'develop' || github.event.inputs.push == 'true' }}
          tags: ghcr.io/${{ github.repository_owner }}/athena_${{ matrix.module }}:latest
