name: Build and Push Docker Images for Modules

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set Matrix
        id: set-matrix
        run: |
          MODULE_NAMES=$(ls -d module_* | jq -R -s -c 'split("\n")[:-1]')
          echo "module=${MODULE_NAMES}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: MODULE_NAME=${{ matrix.module }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.module }}:latest
